package com.stonytark.usefultoolsmod.datagen;

import com.stonytark.usefultoolsmod.UsefultoolsMod;
import com.stonytark.usefultoolsmod.block.ModBlocks;
import net.minecraft.client.data.models.BlockModelGenerators;
import net.minecraft.client.data.models.ItemModelGenerators;
import net.minecraft.client.data.models.ModelProvider;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.data.PackOutput;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.common.data.ExistingFileHelper;
import net.minecraftforge.registries.RegistryObject;

import java.util.stream.Stream;

/**
 * Block model + blockstate provider for {@code runData}.
 *
 * <p>26.1 moved model generation off NeoForge's BlockStateProvider helpers and onto the
 * vanilla {@link ModelProvider}. Forge's vanilla ModelProvider ctor only takes a
 * {@link PackOutput} (no modid arg like NeoForge), and {@link #getKnownBlocks()} returns a
 * {@code Stream<Block>} (not {@code Stream<Holder<Block>>}). We override both to scope the
 * generator to our namespace and to elide the hand-written SpectralInfuser entry.
 *
 * <p>The actual model emission happens via {@link #registerModels} on the two MC
 * generators. {@code BlockModelGenerators#createTrivialCube} is widened to public by our
 * access transformer so we can call it across packages.
 */
public class ModBlockStateProvider extends ModelProvider {

    public ModBlockStateProvider(PackOutput output, ExistingFileHelper existingFileHelper) {
        super(output);
    }

    /** ModelProvider#getName is final, so we can't override it. Name shows up in
     *  runData output as "Model Definitions" — fine for this purpose. */

    /** Standalone item models live in {@link ModItemModelProvider}; report no items
     *  here so the per-provider validator doesn't demand entries we don't emit. */
    @Override
    protected Stream<Item> getKnownItems() {
        return Stream.empty();
    }

    @Override
    protected Stream<Block> getKnownBlocks() {
        return BuiltInRegistries.BLOCK.stream()
                .filter(b -> UsefultoolsMod.MOD_ID.equals(
                        BuiltInRegistries.BLOCK.getKey(b).getNamespace()))
                // SpectralInfuser's blockstate + both orientable_with_bottom models
                // are hand-written under src/main/resources/assets/usefultoolsmod/
                // because the datagen can't represent the multi-variant facing+lit
                // matrix the block needs.
                .filter(b -> b != ModBlocks.SPECTRAL_INFUSER.get());
    }

    @Override
    protected BlockModelGenerators getBlockModelGenerators(BlockStateGeneratorCollector blocks,
                                                            ItemInfoCollector items,
                                                            SimpleModelCollector models) {
        BlockModelGenerators gen = super.getBlockModelGenerators(blocks, items, models);
        // Every mod block gets a trivial cube-all model. Item-models for the BlockItem
        // children are auto-generated by ModelProvider.ItemInfoCollector.finalizeAndValidate
        // based on the registered block model.
        cube(gen, ModBlocks.RGOLDBLOCK);
        cube(gen, ModBlocks.HRBLOCK);
        cube(gen, ModBlocks.RGOLDORE);
        cube(gen, ModBlocks.SEMBLOCK);
        cube(gen, ModBlocks.SOBLOCK);
        cube(gen, ModBlocks.LBLOCK);
        cube(gen, ModBlocks.RGOLD_NETHER_ORE);
        cube(gen, ModBlocks.RGOLD_END_ORE);
        cube(gen, ModBlocks.RGOLD_DEEPSLATE_ORE);
        cube(gen, ModBlocks.HGLOW_BLOCK);
        cube(gen, ModBlocks.RAW_RGOLD_BLOCK);
        cube(gen, ModBlocks.ECTOPLASM_BLOCK);
        cube(gen, ModBlocks.REFINED_ECTOPLASM_BLOCK);
        cube(gen, ModBlocks.HARDENED_COAL_BLOCK);
        cube(gen, ModBlocks.COAL_DUST_BLOCK);
        cube(gen, ModBlocks.OBSHARD_BLOCK);
        cube(gen, ModBlocks.CALCIFIED_AMETHYST_BLOCK);
        cube(gen, ModBlocks.GLACIAL_SHARD_BLOCK);
        cube(gen, ModBlocks.POLISHED_QUARTZ_BLOCK);
        cube(gen, ModBlocks.POLISHED_PRISMARINE_BLOCK);
        return gen;
    }

    private static void cube(BlockModelGenerators gen, RegistryObject<Block> block) {
        gen.createTrivialCube(block.get());
    }
}
